Some small fixes to deb package building scripts.

diff --git a/llvm-frontend/scripts/build_debian b/llvm-frontend/scripts/build_debian
--- a/llvm-frontend/scripts/build_debian
+++ b/llvm-frontend/scripts/build_debian
@@ -49,12 +49,12 @@ function build_and_install {
     export CFLAGS="-O2"
     export CC="gcc"
 
-    export LLVM_BIN_DIR=${LLVM_BIN_DIR:-$HOME/llvm/bin}
-    addToPath "${LLVM_BIN_DIR}"
+    export LLVM_INSTALL_DIR=${LLVM_INSTALL_DIR:-$HOME/llvm}
+    addToPath "${LLVM_INSTALL_DIR}/bin"
 
-    ${FRONTEND_ROOT}/configure > ${log_file} || { rm -rf ${build_tmp_dir}; eexit "Configure failed."; }
-    make > ${log_file} || { rm -rf ${build_tmp_dir}; eexit "Make failed."; }
-    make DESTDIR=${TMP_DIR} install > ${log_file} || { rm -rf ${build_tmp_dir}; eexit "Make install failed."; }
+    ${FRONTEND_ROOT}/configure &> ${log_file} || { rm -rf ${build_tmp_dir}; eexit "Configure failed."; }
+    make &> ${log_file} || { rm -rf ${build_tmp_dir}; eexit "Make failed."; }
+    make DESTDIR=${TMP_DIR} install &> ${log_file} || { rm -rf ${build_tmp_dir}; eexit "Make install failed."; }
     cd ${FRONTEND_ROOT}
     rm -rf ${build_tmp_dir}
 }
